name: epomaker-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<4.0
  - appdirs==1.4.4
  - click>=8.0.1
  - hidapi==0.14.0
  - numpy<2.0
  - opencv-python-headless==4.10.0.82
  - psutil>=6.0.0
  - python-dateutil==2.8.2
  - matplotlib==3.5.3
  - pytest>=6.2.5
